k8s-test-cluster-name:   articulate-test
k8s-test-cluster-ns:   default
k8s-prod-cluster-name:   articulate-prod
k8s-prod-cluster-ns:   default

harbor-project: articulate
articulate-image: articulate
helm_release: articulate
articulate-repo-branch: develop