platform: linux

image_resource:
    type: docker-image
    source:
        repository: pivotalservices/pks-kubectl

inputs:
- name: articulate-helmchart
  path: code
- name: articulate-ci
  path: ci


run:
  path: ./ci/tasks/test-app/task.sh

# params:
#   PKS_API: ((PKS_API))
#   PKS_CLI_USERNAME: ((PKS_CLI_USERNAME))
#   PKS_CLI_PASSWORD: ((PKS_CLI_PASSWORD))
#   k8s-cluster-name: ((k8s-cluster-name))
#   PKS_SKIP_TLS_VERIFY: true