---
    platform: linux
    
    image_resource:
      type: docker-image
      source:
        repository: warroyo90/harbor-scan-resource
    inputs:
      - name: articulate-ci
        path: ci
    run:        
      path: ./ci/tasks/image-scan/scan.sh

    #params:
    #  harbor_host: ((harbor-host))
    #  username: ((harbor-username))
    #  password: ((harbor-password))
    #  repository: ((harbor-host))/hemanth/pks-demo