---
    platform: linux
    
    image_resource:
      type: docker-image
      source:
        repository: warroyo90/harbor-scan-resource
    inputs:
      - name: articulate-ci
        path: ci
      - name: articulate-version
    run:        
      path: ./ci/tasks/image-scan/scan.sh
