---
    platform: linux
    
    image_resource:
      type: docker-image
      source:
        repository: warroyo90/harbor-scan-resource
    inputs:
      - name: articulate-ci
        path: ci
    run:        
      path: ./ci/tasks/image-scan/scan.sh

    #params:
      #harbor_host: ((harbor_host))
      #username: ((harbor-username))
      #password: ((password))
      #repository: ((harbor-host))/hemanth/pks-demo
      #harbor_scan_thresholds: [{"severity": 4,"count": 10},{"severity": 5,"count": 1}]
      #tag: articulate-repo/.git/refs/heads/master