---
    platform: linux
    
    image_resource:
      type: docker-image
      source:
        repository: mikefarah/yq
    inputs:
      - name: articulate-ci
        path: ci
    run:        
      path: ./ci/tasks/image-scan/temp.sh

    params:
      HARBOR_HOST: ((harbor.host))
      HARBOR_USERNAME: ((harbor.username))
      HARBOR_PASSWORD: ((harbor.password))