platform: linux

image_resource:
    type: docker-image
    source:
        repository: pivotalservices/pks-kubectl

inputs:
- name: articulate-ci
  path: ci

run:
  path: ./ci/tasks/switch-blue-green-traffic/task.sh
